/**
 * Include Wrangler's generated binding declarations in SvelteKit's source program.
 *
 * The declaration itself is generated by `wrangler types`; this reference only makes
 * the global `Env` visible to the static Worker entrypoint without duplicating bindings.
 */
/// <reference path="../worker-configuration.d.ts" />
