/**
 * Parser tests.
 *
 * Two halves, and both matter:
 *
 * - **Committed captures** (`tests/fixtures/bytes.ts`, regenerated by
 *   `bun scripts/capture-fixtures.ts`) are parsed and asserted field by field,
 *   including the shapes that break naive parsers: a newline inside a path, a tab
 *   inside a path, a rename whose two paths arrive in separate NUL frames, an
 *   unmerged record with four modes, binary numstat.
 * - **Live regeneration** drives a real repository with the *planners' own argv*
 *   and asserts the same structure, so a fixture can never quietly become a story
 *   about output Git no longer produces.
 *
 * Chunk independence is tested explicitly on the framing layer: the same bytes are
 * fed through the NUL framer one byte at a time and compared with the whole-buffer
 * split. A parser that only works when a record arrives in one piece is a parser
 * that will corrupt a rename on a busy machine.
 */
import { describe, expect, it } from "vitest";
import { realpathSync } from "node:fs";
import {
  CatFileDecoder,
  GitOutputParseError,
  NulFramer,
  parseCommitObject,
  parseFetchPorcelain,
  parseForEachRef,
  parseLsFilesStage,
  parseNameStatus,
  parseNumstat,
  parsePatch,
  parsePushPorcelain,
  parseReflog,
  parseStatus,
  parseTagObject,
  parseWorktreeList,
  planCatFileBatch,
  planDiffNameStatus,
  planDiffNumstat,
  planForEachRef,
  planLsFilesStage,
  planRepositoryLayout,
  planRevList,
  planStashList,
  planStatus,
  planWorktreeList,
  splitNulFrames,
} from "@refyard/git-core";
import { createRepo } from "../support/repo.js";
import {
  BYTE_FIXTURES,
  CAPTURE_GIT_VERSION,
  fixtureBytes,
  type ByteFixtureName,
} from "../fixtures/bytes.js";

const CWD = "wt_aaaaaaaaaaaaaaaa";
const context = { cwdHandle: CWD };

function decode(bytes: Uint8Array): string {
  return new TextDecoder().decode(bytes);
}

describe("status --porcelain=v2 -z", () => {
  it("reads a clean branch header without inventing entries", () => {
    const parsed = parseStatus(fixtureBytes("statusCleanWithBranch"));
    expect(parsed.branch).toEqual({
      seen: true,
      initial: false,
      detached: false,
      oid: "2880c581c186fa19dd10596479a25bd54a9797b5",
      head: "main",
    });
    expect(parsed.records).toEqual([]);
    expect(parsed.upstream).toBeNull();
    expect(parsed.aheadBehind).toBeNull();
  });

  it("reads every record type, keeping raw bytes for paths", () => {
    const parsed = parseStatus(fixtureBytes("statusAllRecordTypes"));
    const kinds = parsed.records.map((record) => record.kind);
    expect(kinds).toEqual([
      "ordinary",
      "ordinary",
      "renamed",
      "untracked",
      "untracked",
      "ignored",
    ]);

    const modified = parsed.records[0];
    expect(modified?.indexStatus).toBe("M");
    expect(modified?.worktreeStatus).toBe("M");
    expect(decode(modified?.path ?? new Uint8Array())).toBe("base.txt");
    expect(modified?.modes).toEqual({
      head: "100644",
      index: "100644",
      worktree: "100644",
    });

    // A staged deletion has a zeroed index OID, which must read as absent rather
    // than as forty zeros the UI would then try to look up.
    const deleted = parsed.records[1];
    expect(deleted?.indexStatus).toBe("D");
    expect(deleted?.oids.head).toBe("2d030d7bc1bbfbdee332aaf691447b30cdea375b");
    expect(deleted?.oids.index).toBeNull();
    expect(deleted?.modes.index).toBeNull();

    // The rename: new path in its own record, original path in the next frame.
    const renamed = parsed.records[2];
    expect(renamed?.kind).toBe("renamed");
    expect(decode(renamed?.path ?? new Uint8Array())).toBe(
      "moved 新\tname.txt",
    );
    expect(decode(renamed?.originalPath ?? new Uint8Array())).toBe(
      "rename-src.txt",
    );
    expect(renamed?.score).toBe(100);
  });

  it("keeps a newline inside a path instead of splitting the record", () => {
    const parsed = parseStatus(fixtureBytes("statusAllRecordTypes"));
    const untracked = parsed.records.filter(
      (record) => record.kind === "untracked",
    );
    expect(untracked.map((record) => decode(record.path))).toEqual([
      "line\nbreak.txt",
      "tab\tname.txt",
    ]);
  });

  it("reads an unmerged record with its four modes and three object names", () => {
    const parsed = parseStatus(fixtureBytes("statusUnmerged"));
    expect(parsed.records).toHaveLength(1);
    const unmerged = parsed.records[0];
    expect(unmerged?.kind).toBe("unmerged");
    expect(unmerged?.indexStatus).toBe("U");
    expect(unmerged?.worktreeStatus).toBe("U");
    expect(unmerged?.stages.map((stage) => stage.stage)).toEqual([1, 2, 3]);
    expect(unmerged?.stages.map((stage) => stage.mode)).toEqual([
      "100644",
      "100644",
      "100644",
    ]);
    // Cross-check against the index listing of the same repository state: the
    // stage-1 object of the conflict must be the same commit in both reads.
    const index = parseLsFilesStage(fixtureBytes("lsFilesUnmerged"));
    expect(unmerged?.stages.map((stage) => stage.oid)).toEqual(
      index.map((entry) => entry.oid),
    );
    expect(new Set(unmerged?.stages.map((stage) => stage.oid)).size).toBe(3);
    expect(decode(unmerged?.path ?? new Uint8Array())).toBe("base.txt");
  });

  it("matches the same structure when the bytes arrive one at a time", () => {
    const bytes = fixtureBytes("statusAllRecordTypes");
    const framer = new NulFramer("status");
    const frames: Uint8Array[] = [];
    for (const byte of bytes) {
      frames.push(...framer.push(Uint8Array.of(byte)));
    }
    framer.finish();
    const wholeBuffer = splitNulFrames(bytes, "status");
    expect(frames.map(decode)).toEqual(wholeBuffer.map(decode));

    // And the reassembled stream parses identically to the original.
    const reassembled = new TextEncoder().encode(
      frames.map(decode).join("\u0000") + "\u0000",
    );
    expect(parseStatus(reassembled).records.length).toBe(
      parseStatus(bytes).records.length,
    );
  });

  it("refuses an unknown record type rather than dropping it", () => {
    // 'x' is not a porcelain v2 record. Skipping it would silently hide a change
    // from the UI, which is worse than a failed read.
    expect(() =>
      parseStatus(
        new TextEncoder().encode("x A. N... 100644 100644 100644 0 0 p\u0000"),
      ),
    ).toThrowError(GitOutputParseError);
  });

  it("refuses a stream that ends inside a record", () => {
    expect(() =>
      parseStatus(new TextEncoder().encode("1 .M N... 100644 100644 100644")),
    ).toThrowError(/after the last NUL/);
  });

  it("refuses a rename record whose original path frame is missing", () => {
    const frame = "2 R. N... 100644 100644 100644 aaaa bbbb R100 new.txt\u0000";
    expect(() => parseStatus(new TextEncoder().encode(frame))).toThrowError(
      /original path frame/,
    );
  });

  it("ignores an unknown header but keeps the known ones", () => {
    const bytes = new TextEncoder().encode(
      "# branch.oid 00a6d892293f4d9b75084493e2bc1981f71aa5bc\u0000" +
        "# branch.head main\u0000" +
        "# branch.upstream origin/main\u0000" +
        "# branch.ab +2 -3\u0000" +
        "# branch.future-header something\u0000",
    );
    const parsed = parseStatus(bytes);
    expect(parsed.upstream).toBe("origin/main");
    expect(parsed.aheadBehind).toEqual({ ahead: 2, behind: 3 });
    expect(parsed.branch.head).toBe("main");
  });
});

describe("diff --numstat -z and --name-status -z", () => {
  it("reads counts, a rename with two frames and a binary change", () => {
    const numstat = parseNumstat(fixtureBytes("numstatRename"));
    expect(numstat).toHaveLength(3);
    expect(numstat[0]).toMatchObject({
      insertions: 2,
      deletions: 1,
      binary: false,
    });
    expect(decode(numstat[0]?.path ?? new Uint8Array())).toBe("base.txt");
    expect(decode(numstat[1]?.path ?? new Uint8Array())).toBe("delete-me.txt");
    expect(decode(numstat[2]?.originalPath ?? new Uint8Array())).toBe(
      "rename-src.txt",
    );
    expect(decode(numstat[2]?.path ?? new Uint8Array())).toBe(
      "moved 新\tname.txt",
    );

    const binary = parseNumstat(fixtureBytes("numstatBinary"));
    const binDat = binary.find((entry) => decode(entry.path) === "bin.dat");
    expect(binDat?.binary).toBe(true);
    expect(binDat?.insertions).toBeNull();
  });

  it("reads name-status with the score and both rename paths", () => {
    const entries = parseNameStatus(fixtureBytes("nameStatusRename"));
    expect(entries.map((entry) => entry.changeKind)).toEqual([
      "modified",
      "deleted",
      "renamed",
    ]);
    expect(entries[2]?.score).toBe(100);
    expect(decode(entries[2]?.originalPath ?? new Uint8Array())).toBe(
      "rename-src.txt",
    );
    expect(decode(entries[2]?.path ?? new Uint8Array())).toBe(
      "moved 新\tname.txt",
    );
  });

  it("reads an unmerged name-status listing, where the same path appears twice", () => {
    const entries = parseNameStatus(fixtureBytes("nameStatusUnmerged"));
    expect(entries.map((entry) => entry.rawStatus)).toEqual(["U", "M"]);
    expect(entries.every((entry) => decode(entry.path) === "base.txt")).toBe(
      true,
    );
  });

  it("refuses a truncated rename", () => {
    expect(() =>
      parseNumstat(new TextEncoder().encode("0\t0\t\u0000old.txt\u0000")),
    ).toThrowError(/two path frames/);
  });
});

describe("ls-files --stage -z", () => {
  it("reads mode, object name, stage and a path that contains a tab", () => {
    const entries = parseLsFilesStage(fixtureBytes("lsFilesStage"));
    expect(entries.length).toBeGreaterThan(0);
    const renamed = entries.find(
      (entry) => decode(entry.path) === "moved 新\tname.txt",
    );
    expect(renamed?.mode).toBe("100644");
    expect(renamed?.stage).toBe(0);
    expect(renamed?.gitlink).toBe(false);
  });

  it("reads unmerged stages 1, 2 and 3 for one path", () => {
    const entries = parseLsFilesStage(fixtureBytes("lsFilesUnmerged"));
    expect(entries.map((entry) => entry.stage)).toEqual([1, 2, 3]);
    expect(entries[1]?.oid).toBe("21d65f9bcc9b45c737fa7ba476aeb90a0d296cbd");
  });

  it("marks a gitlink, which is a commit in the index rather than a file", () => {
    const entries = parseLsFilesStage(fixtureBytes("lsFilesGitlink"));
    const gitlink = entries.find((entry) => entry.gitlink);
    expect(gitlink?.mode).toBe("160000");
    expect(decode(gitlink?.path ?? new Uint8Array())).toBe("vendor/sub");
  });
});

describe("for-each-ref", () => {
  it("reads refs with NUL fields and newline records", () => {
    const refs = parseForEachRef(fixtureBytes("forEachRef"));
    const main = refs.find((ref) => ref.refName === "refs/heads/main");
    expect(main?.objectType).toBe("commit");
    expect(main?.isHead).toBe(true);
    expect(main?.upstream).toBeNull();
    const other = refs.find((ref) => ref.refName === "refs/heads/other");
    expect(other?.isHead).toBe(false);
  });

  it("distinguishes an annotated tag from a lightweight one", () => {
    const refs = parseForEachRef(fixtureBytes("forEachRefWithTags"));
    const annotated = refs.find((ref) => ref.refName === "refs/tags/annotated");
    const lightweight = refs.find(
      (ref) => ref.refName === "refs/tags/lightweight",
    );
    expect(annotated?.objectType).toBe("tag");
    expect(annotated?.peeledOid).toMatch(/^[0-9a-f]{40}$/);
    expect(lightweight?.objectType).toBe("commit");
    expect(lightweight?.peeledOid).toBeNull();
  });

  it("refuses a field count that does not match the format it asked for", () => {
    expect(() =>
      parseForEachRef(new TextEncoder().encode("refs/heads/main\u0000aaaa\n")),
    ).toThrowError(/expected 8 fields/);
  });
});

describe("worktree list --porcelain -z", () => {
  it("reads the primary worktree block", () => {
    const worktrees = parseWorktreeList(fixtureBytes("worktreeList"));
    expect(worktrees).toHaveLength(1);
    expect(worktrees[0]?.branchRef).toBe("refs/heads/main");
    expect(worktrees[0]?.bare).toBe(false);
    expect(worktrees[0]?.detached).toBe(false);
    expect(
      decode(worktrees[0]?.pathBytes ?? new Uint8Array()).endsWith("/repo"),
    ).toBe(true);
  });

  it("keeps a lock reason that contains a newline", () => {
    const bytes = new TextEncoder().encode(
      "worktree /tmp/wt\u0000HEAD 0000000000000000000000000000000000000000\u0000detached\u0000locked waiting\nfor disk\u0000\u0000",
    );
    const worktrees = parseWorktreeList(bytes);
    expect(worktrees[0]?.locked).toBe(true);
    expect(decode(worktrees[0]?.lockReasonBytes ?? new Uint8Array())).toBe(
      "waiting\nfor disk",
    );
  });
});

describe("cat-file --batch", () => {
  it("reads a framed object body and a missing object", () => {
    const decoder = new CatFileDecoder();
    const entries = decoder.push(fixtureBytes("catFileCommit"));
    decoder.finish();
    expect(entries).toHaveLength(1);
    const first = entries[0];
    expect(first !== undefined && "type" in first && first.type).toBe("commit");
    if (first === undefined || "missing" in first) {
      throw new Error("expected a commit object");
    }
    const commit = parseCommitObject(first.body);
    expect(commit.treeOid).toMatch(/^[0-9a-f]{40}$/);
    expect(commit.parentOids.length).toBeGreaterThan(0);
    expect(decode(commit.author.nameBytes)).toBe("Fixture Author");
    expect(decode(commit.author.emailBytes)).toBe("author@refyard.invalid");
    expect(decode(commit.messageBytes).trim()).toBe("main side");
    expect(commit.signed).toBe(false);
  });

  it("reports a missing object instead of failing the whole batch", () => {
    const decoder = new CatFileDecoder();
    const entries = decoder.push(fixtureBytes("catFileMissing"));
    decoder.finish();
    expect(entries).toHaveLength(1);
    expect(entries[0]).toHaveProperty("missing", "0".repeat(40));
  });

  it("assembles the same objects when the body is split across chunks", () => {
    const bytes = fixtureBytes("catFileCommit");
    for (const cut of [1, 7, 40, bytes.byteLength - 1]) {
      const decoder = new CatFileDecoder();
      const entries = [
        ...decoder.push(bytes.subarray(0, cut)),
        ...decoder.push(bytes.subarray(cut)),
      ];
      decoder.finish();
      expect(entries, `split at ${cut}`).toHaveLength(1);
    }
  });

  it("refuses a stream that ends inside an object body", () => {
    const bytes = fixtureBytes("catFileCommit");
    const decoder = new CatFileDecoder();
    decoder.push(bytes.subarray(0, bytes.byteLength - 5));
    expect(() => decoder.finish()).toThrowError(/header promising/);
  });

  it("marks a signed commit and preserves a multi-line signature header", () => {
    const header = [
      "tree 4b825dc642cb6eb9a060e54bf8d69288fbee4904",
      "parent 0000000000000000000000000000000000000001",
      "author Person <person@example.invalid> 1767225600 +0000",
      "committer Person <person@example.invalid> 1767225600 +0000",
      "gpgsig -----BEGIN PGP SIGNATURE-----",
      " ",
      " iQIzBAABCAAdFiEEexample",
      " -----END PGP SIGNATURE-----",
      "",
      "signed subject",
      "",
    ].join("\n");
    const commit = parseCommitObject(new TextEncoder().encode(header));
    expect(commit.signed).toBe(true);
    expect(commit.parentOids).toEqual([
      "0000000000000000000000000000000000000001",
    ]);
    expect(decode(commit.messageBytes).trim()).toBe("signed subject");
  });

  it("reads an annotated tag object", () => {
    const body = [
      "object 0123456789abcdef0123456789abcdef01234567",
      "type commit",
      "tag v1.0.0",
      "tagger Person <person@example.invalid> 1767225600 +0800",
      "",
      "release notes",
      "",
    ].join("\n");
    const tag = parseTagObject(new TextEncoder().encode(body));
    expect(tag.tagName).toBe("v1.0.0");
    expect(tag.objectType).toBe("commit");
    expect(tag.tagger?.timezoneOffset).toBe("+0800");
    expect(decode(tag.messageBytes).trim()).toBe("release notes");
  });
});

describe("patches", () => {
  it("parses hunks, line kinds and a missing trailing newline", () => {
    const bytes = fixtureBytes("patchText");
    const result = parsePatch(bytes);
    expect(result.truncated).toBe(false);
    expect(result.files).toHaveLength(1);
    const file = result.files[0];
    expect(file?.body.kind).toBe("text");
    if (file?.body.kind !== "text") {
      throw new Error("expected a text patch");
    }
    const hunk = file.body.hunks[0];
    expect(hunk?.oldLines).toBe(1);
    expect(hunk?.lines.map((line) => line.kind)).toEqual(["remove", "add"]);
    expect(hunk?.lines[0]?.text).toBe("base");
  });

  it("keeps the no-newline marker attached to its line rather than dropping it", () => {
    const patch = [
      "diff --git a/f.txt b/f.txt",
      "index 1111111..2222222 100644",
      "--- a/f.txt",
      "+++ b/f.txt",
      "@@ -1 +1 @@",
      "-old",
      "\\ No newline at end of file",
      "+new",
      "\\ No newline at end of file",
      "",
    ].join("\n");
    const result = parsePatch(new TextEncoder().encode(patch));
    const body = result.files[0]?.body;
    if (body?.kind !== "text") {
      throw new Error("expected a text patch");
    }
    expect(body.hunks[0]?.lines.map((line) => line.noNewline)).toEqual([
      true,
      true,
    ]);
  });

  it("reports a binary change as binary, with modes but no hunks", () => {
    const patch = [
      "diff --git a/bin.dat b/bin.dat",
      "index 1111111..2222222 100644",
      "Binary files a/bin.dat and b/bin.dat differ",
      "",
    ].join("\n");
    const result = parsePatch(new TextEncoder().encode(patch));
    expect(result.files[0]?.body.kind).toBe("binary");
  });

  it("reports a submodule change with its object names instead of a fake patch", () => {
    const patch = [
      "diff --git a/vendor/sub b/vendor/sub",
      "index 1111111..2222222 160000",
      "--- a/vendor/sub",
      "+++ b/vendor/sub",
      "@@ -1 +1 @@",
      "-Subproject commit 0123456789abcdef0123456789abcdef01234567",
      "+Subproject commit 89abcdef0123456789abcdef0123456789abcdef",
      "",
    ].join("\n");
    const result = parsePatch(new TextEncoder().encode(patch));
    const body = result.files[0]?.body;
    expect(body?.kind).toBe("submodule");
    if (body?.kind !== "submodule") {
      throw new Error("expected a submodule change");
    }
    expect(body.oldOid).toBe("0123456789abcdef0123456789abcdef01234567");
    expect(body.newOid).toBe("89abcdef0123456789abcdef0123456789abcdef");
  });

  it("reports a mode-only change as modeOnly rather than as an empty patch", () => {
    const result = parsePatch(fixtureBytes("patchModeChange"));
    expect(result.files[0]?.body.kind).toBe("modeOnly");
    expect(result.files[0]?.oldMode).toBe("100644");
    expect(result.files[0]?.newMode).toBe("100755");
  });

  it("marks a patch that hit the line bound as truncated, never as complete", () => {
    const bytes = fixtureBytes("patchText");
    const result = parsePatch(bytes, { maxLines: 2 });
    expect(result.truncated).toBe(true);
  });
});

describe("remote porcelain", () => {
  it("reads push output for a new branch, an up-to-date ref and a fast-forward", () => {
    const created = parsePushPorcelain(fixtureBytes("pushNewBranch"));
    expect(created.everythingUpToDate).toBe(false);
    expect(created.remote).toContain("remote.git");
    expect(created.refs[0]?.status).toBe("new");
    expect(created.refs[0]?.to).toBe("refs/heads/main");

    const upToDate = parsePushPorcelain(fixtureBytes("pushUpToDate"));
    expect(upToDate.refs[0]?.status).toBe("upToDate");

    const fastForward = parsePushPorcelain(fixtureBytes("pushFastForward"));
    expect(fastForward.refs[0]?.status).toBe("fastForward");
    expect(fastForward.refs[0]?.summary).toMatch(
      /^[0-9a-f]{7}\.\.[0-9a-f]{7}$/,
    );
  });

  it("reads a rejected push from output produced by a real non-fast-forward", () => {
    const rejected = parsePushPorcelain(fixtureBytes("pushRejected"));
    expect(rejected.refs[0]?.status).toBe("rejected");
    expect(rejected.refs[0]?.summary).toContain("non-fast-forward");
  });

  it("reads a forced update as forced, not as a fast-forward", () => {
    const forced = parsePushPorcelain(fixtureBytes("pushForced"));
    expect(forced.refs[0]?.status).toBe("forced");
  });

  it("reads fetch porcelain, which is a different format from push", () => {
    const updated = parseFetchPorcelain(fixtureBytes("fetchUpdate"));
    expect(updated.refs).toHaveLength(1);
    expect(updated.refs[0]?.localRef).toBe("refs/remotes/origin/main");
    expect(updated.refs[0]?.oldOid).toMatch(/^[0-9a-f]{40}$/);
    expect(updated.refs[0]?.newOid).not.toBe(updated.refs[0]?.oldOid);

    const nothing = parseFetchPorcelain(fixtureBytes("fetchNoChange"));
    expect(nothing.refs).toEqual([]);
    expect(nothing.diagnostics).toEqual([]);
  });
});

describe("reflog and stashes", () => {
  it("reads stash entries with a locator, object name and subject", () => {
    const records = parseReflog(fixtureBytes("stashList"));
    expect(records).toHaveLength(1);
    expect(records[0]?.locator).toBe("stash@{0}");
    expect(records[0]?.oid).toMatch(/^[0-9a-f]{40}$/);
    // The fixture's stash message was two lines; Git stores the reflog subject on
    // one line, so the newline arrives as a space. A parser that assumed a
    // multi-line subject would mis-frame every following record.
    expect(decode(records[0]?.subjectBytes ?? new Uint8Array())).toBe(
      "On main: line one line two",
    );
    expect(records[0]?.timestamp).toBeGreaterThan(1_700_000_000);
  });
});

describe("repository layout", () => {
  it("reads one value per line, with an absolute git dir and the object format", () => {
    const lines = decode(fixtureBytes("repositoryLayout")).trim().split("\n");
    expect(lines).toHaveLength(6);
    expect(lines[0]?.startsWith("/")).toBe(true);
    expect(lines[1]?.startsWith("/")).toBe(true);
    expect(["true", "false"]).toContain(lines[3]);
    expect(["sha1", "sha256"]).toContain(lines[4]);
    expect(["true", "false"]).toContain(lines[5]);
  });
});

describe("the same parsers, against repositories built now", () => {
  it("round-trips status through the planner's argv on a live repository", async () => {
    const repo = await createRepo({ initialCommit: true });
    try {
      await repo.write("space 中文.txt", "one\n");
      await repo.write("line\nbreak.txt", "two\n");
      await repo.commitAll("paths");
      await repo.write("space 中文.txt", "changed\n");

      const plan = planStatus(context, {
        showStash: true,
        includeIgnored: false,
      });
      const stdout = await repo.git(plan.argv);
      const parsed = parseStatus(stdout);

      expect(parsed.branch.head).toBe("main");
      expect(parsed.branch.oid).toBe(await repo.headOid());
      expect(parsed.records).toHaveLength(1);
      expect(parsed.records[0]?.indexStatus).toBe(".");
      expect(parsed.records[0]?.worktreeStatus).toBe("M");
      expect(decode(parsed.records[0]?.path ?? new Uint8Array())).toBe(
        "space 中文.txt",
      );
    } finally {
      await repo.dispose();
    }
  });

  it("round-trips a rename through name-status and numstat on a live repository", async () => {
    const repo = await createRepo({ initialCommit: true });
    try {
      await repo.write("before 名字.txt", "content\n");
      await repo.commitAll("add");
      await repo.git(["mv", "before 名字.txt", "after\t名字.txt"]);

      const nameStatus = parseNameStatus(
        await repo.git(planDiffNameStatus(context, { cached: true }).argv),
      );
      expect(nameStatus[0]?.changeKind).toBe("renamed");
      expect(decode(nameStatus[0]?.originalPath ?? new Uint8Array())).toBe(
        "before 名字.txt",
      );
      expect(decode(nameStatus[0]?.path ?? new Uint8Array())).toBe(
        "after\t名字.txt",
      );

      const numstat = parseNumstat(
        await repo.git(planDiffNumstat(context, { cached: true }).argv),
      );
      expect(decode(numstat[0]?.path ?? new Uint8Array())).toBe(
        "after\t名字.txt",
      );
    } finally {
      await repo.dispose();
    }
  });

  it("round-trips refs, the index, worktree list, stash list and history on a live repository", async () => {
    const repo = await createRepo({ initialCommit: true });
    try {
      await repo.write("b.txt", "b\n");
      await repo.commitAll("second");

      const refs = parseForEachRef(
        await repo.git(planForEachRef(context).argv),
      );
      expect(refs.map((ref) => ref.refName)).toContain("refs/heads/main");
      expect(
        refs.find((ref) => ref.refName === "refs/heads/main")?.isHead,
      ).toBe(true);

      const index = parseLsFilesStage(
        await repo.git(planLsFilesStage(context).argv),
      );
      expect(index.map((entry) => decode(entry.path))).toEqual([
        "a.txt",
        "b.txt",
      ]);

      const worktrees = parseWorktreeList(
        await repo.git(planWorktreeList(context).argv),
      );
      expect(worktrees).toHaveLength(1);
      expect(worktrees[0]?.branchRef).toBe("refs/heads/main");

      await repo.write("a.txt", "stash me\n");
      await repo.git(["stash", "push", "--message=live stash"]);
      const stashes = parseReflog(await repo.git(planStashList(context).argv));
      expect(stashes).toHaveLength(1);
      expect(decode(stashes[0]?.subjectBytes ?? new Uint8Array())).toContain(
        "live stash",
      );
      expect(stashes[0]?.locator).toBe("stash@{0}");

      const head = await repo.headOid();
      const revList = planRevList(context, {
        tips: ["HEAD"],
        maxCount: 10,
        skip: 0,
      });
      const topology = decode(
        await repo.git(revList.argv, { stdin: revList.stdin }),
      );
      const lines = topology.trim().split("\n");
      // Two commits: the tip line carries its parent, and the root line has none.
      expect(lines).toHaveLength(2);
      const tipFields = lines[0]?.split(" ") ?? [];
      const rootFields = lines[1]?.split(" ") ?? [];
      expect(tipFields[0]).toBe(head);
      expect(tipFields).toHaveLength(2);
      expect(rootFields).toHaveLength(1);
      expect(tipFields[1]).toBe(rootFields[0]);

      const catFile = planCatFileBatch(context, [head]);
      const batch = new CatFileDecoder();
      const objects = batch.push(
        await repo.git(catFile.argv, { stdin: catFile.stdin }),
      );
      batch.finish();
      const first = objects[0];
      if (first === undefined || "missing" in first) {
        throw new Error("expected a commit object");
      }
      expect(decode(parseCommitObject(first.body).messageBytes).trim()).toBe(
        "second",
      );
    } finally {
      await repo.dispose();
    }
  });

  it("reads the repository layout with absolute paths", async () => {
    const repo = await createRepo({ initialCommit: true });
    try {
      const layout = decode(await repo.git(planRepositoryLayout(context).argv))
        .trim()
        .split("\n");
      // Git resolves symlinks in the paths it reports (`/var` is `/private/var` on
      // macOS), so the comparison is against the resolved fixture path.
      const resolvedRoot = realpathSync(repo.root);
      expect(layout[0]).toBe(`${resolvedRoot}/.git`);
      expect(layout[1]).toBe(`${resolvedRoot}/.git`);
      expect(layout[2]).toBe(resolvedRoot);
      expect(layout[3]).toBe("false");
      expect(layout[4]).toBe("sha1");
      expect(layout[5]).toBe("false");
    } finally {
      await repo.dispose();
    }
  });
});

describe("fixture provenance", () => {
  it("records the Git version the fixtures were captured from", () => {
    // A fixture is only trustworthy with the version that produced it; when this
    // changes, the fixtures must be regenerated and the diff reviewed.
    expect(CAPTURE_GIT_VERSION).toMatch(/^git version \d+\.\d+\.\d+/);
    expect(Object.keys(BYTE_FIXTURES)).toHaveLength(30);
  });

  it("names the command for every fixture", () => {
    // `fetchNoChange` is empty *because* Git printed nothing when there was
    // nothing to fetch; that emptiness is the case being captured.
    const legitimatelyEmpty = new Set(["fetchNoChange"]);
    for (const [name, fixture] of Object.entries(BYTE_FIXTURES)) {
      expect(fixture.command, `${name} has no command`).toMatch(/^git /);
      if (!legitimatelyEmpty.has(name)) {
        expect(fixture.bytes.length, `${name} is empty`).toBeGreaterThan(0);
      }
    }
  });

  it("keeps a fixture for each shape the parsers are written against", () => {
    const required: ByteFixtureName[] = [
      "statusCleanWithBranch",
      "statusAllRecordTypes",
      "statusUnmerged",
      "statusWithSubmodule",
      "statusModeAndBinaryChange",
      "numstatRename",
      "numstatBinary",
      "nameStatusRename",
      "nameStatusUnmerged",
      "lsFilesStage",
      "lsFilesUnmerged",
      "lsFilesGitlink",
      "forEachRef",
      "forEachRefWithTags",
      "worktreeList",
      "catFileCommit",
      "catFileMissing",
      "patchText",
      "patchModeChange",
      "patchSubmodule",
      "pushNewBranch",
      "pushUpToDate",
      "pushFastForward",
      "pushRejected",
      "pushForced",
      "fetchUpdate",
      "fetchNoChange",
      "stashList",
      "repositoryLayout",
    ];
    for (const name of required) {
      // Presence, not non-emptiness: `fetchNoChange` exists to be empty.
      expect(Object.hasOwn(BYTE_FIXTURES, name), `${name} is missing`).toBe(
        true,
      );
    }
  });
});
