/**
 * Named registry of every schema that crosses the wire.
 *
 * JSON Schema generation, OpenAPI-style documentation and the drift check all
 * read this list, so a new public shape is added in exactly one place. The names
 * are the `$defs` keys, which is what makes a generated reference resolvable.
 */
import type { z } from "zod";
import {
  allowedRootIdSchema,
  apiMajorSchema,
  clientRequestIdSchema,
  cursorSchema,
  displayPathSchema,
  objectFormatSchema,
  objectIdSchema,
  operationIdSchema,
  pathIdSchema,
  previewTokenSchema,
  repositoryIdSchema,
  serviceInstanceIdSchema,
  snapshotIdSchema,
  timestampSchema,
  worktreeIdSchema,
} from "./ids.js";
import { runtimeLimitsSchema } from "./limits.js";
import {
  branchNameSchema,
  commitMessageSchema,
  fullRefNameSchema,
  pathSelectionSchema,
  plainPathSelectionSchema,
  remoteNameSchema,
  remoteUrlSchema,
  stashLocatorSchema,
  stashRefSchema,
  tagNameSchema,
} from "./names.js";
import { OPERATION_SCHEMAS } from "./operations.js";
import { MutationRequestSchema, operationAcceptedSchema } from "./requests.js";
import { problemResponseSchema, problemSchema } from "./errors.js";
import {
  capabilitiesQuerySchema,
  capabilitiesResponseSchema,
  cancelOperationRequestSchema,
  commitDetailSchema,
  commitSummarySchema,
  diffFileSchema,
  diffQuerySchema,
  diffResponseSchema,
  eventEnvelopeSchema,
  eventPayloadSchema,
  eventsQuerySchema,
  filePatchSchema,
  filesystemEntriesQuerySchema,
  filesystemEntriesResponseSchema,
  filesystemEntrySchema,
  gitCapabilitiesSchema,
  headStateSchema,
  healthResponseSchema,
  historyPageSchema,
  historyQuerySchema,
  operationQuerySchema,
  operationsListQuerySchema,
  operationRecordSchema,
  operationResultSchema,
  operationsListResponseSchema,
  patchHunkSchema,
  patchLineSchema,
  pathEncodingSchema,
  previewsRequestSchema,
  previewsResponseSchema,
  readKindSchema,
  refEntrySchema,
  refsSnapshotSchema,
  remoteRefEntrySchema,
  repositoriesQuerySchema,
  registerRepositoryRequestSchema,
  revokeRepositoryRequestSchema,
  repositoryQuerySchema,
  repositorySummarySchema,
  repositoriesResponseSchema,
  sessionExchangeRequestSchema,
  sessionExchangeResponseSchema,
  stashEntrySchema,
  stashesResponseSchema,
  statusEntrySchema,
  statusSnapshotSchema,
  submoduleStatusSchema,
  submoduleSummarySchema,
  submodulesResponseSchema,
  tagEntrySchema,
  unavailableReasonSchema,
  unmergedStageSchema,
  worktreeQuerySchema,
  worktreeSummarySchema,
  worktreesResponseSchema,
} from "./reads.js";
import {
  mutationTargetSchema,
  relativeDestinationSchema,
  repositoryTargetSchema,
  targetKindSchema,
  workspaceTargetSchema,
  worktreeTargetSchema,
} from "./targets.js";

/**
 * Every named public schema. Keys become `$defs` entries, so they must be unique
 * and must match the `id` metadata on the schema itself (a test asserts this).
 */
export const CONTRACT_SCHEMAS: Readonly<Record<string, z.ZodType>> = {
  ApiMajor: apiMajorSchema,
  ServiceInstanceId: serviceInstanceIdSchema,
  AllowedRootId: allowedRootIdSchema,
  RepositoryId: repositoryIdSchema,
  WorktreeId: worktreeIdSchema,
  PathId: pathIdSchema,
  SnapshotId: snapshotIdSchema,
  OperationId: operationIdSchema,
  PreviewToken: previewTokenSchema,
  Cursor: cursorSchema,
  ClientRequestId: clientRequestIdSchema,
  ObjectId: objectIdSchema,
  ObjectFormat: objectFormatSchema,
  Timestamp: timestampSchema,
  DisplayPath: displayPathSchema,
  RuntimeLimits: runtimeLimitsSchema,
  TargetKind: targetKindSchema,
  RelativeDestination: relativeDestinationSchema,
  WorkspaceTarget: workspaceTargetSchema,
  RepositoryTarget: repositoryTargetSchema,
  WorktreeTarget: worktreeTargetSchema,
  MutationTarget: mutationTargetSchema,
  BranchName: branchNameSchema,
  TagName: tagNameSchema,
  RemoteName: remoteNameSchema,
  FullRefName: fullRefNameSchema,
  RemoteUrl: remoteUrlSchema,
  StashLocator: stashLocatorSchema,
  StashRef: stashRefSchema,
  CommitMessage: commitMessageSchema,
  PathSelection: pathSelectionSchema,
  PlainPathSelection: plainPathSelectionSchema,
  MutationRequest: MutationRequestSchema,
  OperationAccepted: operationAcceptedSchema,
  Problem: problemSchema,
  ProblemResponse: problemResponseSchema,
  HealthResponse: healthResponseSchema,
  SessionExchangeRequest: sessionExchangeRequestSchema,
  SessionExchangeResponse: sessionExchangeResponseSchema,
  ReadKind: readKindSchema,
  GitCapabilities: gitCapabilitiesSchema,
  UnavailableReason: unavailableReasonSchema,
  CapabilitiesResponse: capabilitiesResponseSchema,
  HeadState: headStateSchema,
  RepositorySummary: repositorySummarySchema,
  RepositoriesResponse: repositoriesResponseSchema,
  FilesystemEntry: filesystemEntrySchema,
  FilesystemEntriesQuery: filesystemEntriesQuerySchema,
  FilesystemEntriesResponse: filesystemEntriesResponseSchema,
  PathEncoding: pathEncodingSchema,
  SubmoduleStatus: submoduleStatusSchema,
  UnmergedStage: unmergedStageSchema,
  StatusEntry: statusEntrySchema,
  StatusSnapshot: statusSnapshotSchema,
  CommitSummary: commitSummarySchema,
  CommitDetail: commitDetailSchema,
  HistoryPage: historyPageSchema,
  RefEntry: refEntrySchema,
  RemoteRefEntry: remoteRefEntrySchema,
  TagEntry: tagEntrySchema,
  RefsSnapshot: refsSnapshotSchema,
  PatchLine: patchLineSchema,
  PatchHunk: patchHunkSchema,
  FilePatch: filePatchSchema,
  DiffFile: diffFileSchema,
  DiffResponse: diffResponseSchema,
  WorktreeSummary: worktreeSummarySchema,
  WorktreesResponse: worktreesResponseSchema,
  SubmoduleSummary: submoduleSummarySchema,
  SubmodulesResponse: submodulesResponseSchema,
  StashEntry: stashEntrySchema,
  StashesResponse: stashesResponseSchema,
  OperationResult: operationResultSchema,
  OperationRecord: operationRecordSchema,
  OperationsListResponse: operationsListResponseSchema,
  CancelOperationRequest: cancelOperationRequestSchema,
  PreviewsRequest: previewsRequestSchema,
  PreviewsResponse: previewsResponseSchema,
  EventPayload: eventPayloadSchema,
  EventEnvelope: eventEnvelopeSchema,
  CapabilitiesQuery: capabilitiesQuerySchema,
  RepositoriesQuery: repositoriesQuerySchema,
  RegisterRepositoryRequest: registerRepositoryRequestSchema,
  RevokeRepositoryRequest: revokeRepositoryRequestSchema,
  RepositoryQuery: repositoryQuerySchema,
  WorktreeQuery: worktreeQuerySchema,
  HistoryQuery: historyQuerySchema,
  DiffQuery: diffQuerySchema,
  OperationQuery: operationQuerySchema,
  OperationsListQuery: operationsListQuerySchema,
  EventsQuery: eventsQuerySchema,
};

/** Names of the individual operation payload schemas, keyed by operation kind. */
export function operationSchemaId(
  kind: keyof typeof OPERATION_SCHEMAS,
): string {
  const id = OPERATION_SCHEMAS[kind].meta()?.id;
  if (typeof id !== "string" || id.length === 0) {
    throw new Error(`operation ${kind} has no schema id metadata`);
  }
  return id;
}
