/**
 * `@refyard/git-ui` — the workbench components.
 *
 * Everything here is driven by props and an injected `GitService`, and nothing imports
 * `$app/*`, so the same components can be mounted by the SvelteKit app, by a future
 * Kunkun plugin, or by a test harness. Routing and connection configuration are the
 * app's job; this package renders Git data and the states around it.
 *
 * The primitives under `components/ui/` are generated by the shadcn-svelte CLI
 * (`components.json` lives in this package) and then made self-contained by
 * `scripts/fix-shadcn-imports.ts`, which rewrites the CLI's `$lib/…` alias imports to
 * relative ones — this package is deliberately not a SvelteKit app, so it cannot rely on
 * that alias. Prefer generating another component over writing one.
 */

export {
  Badge,
  badgeVariants,
  type BadgeTone,
  type BadgeVariant,
} from "./components/ui/badge/index.js";
export {
  Button,
  buttonVariants,
  type ButtonSize,
  type ButtonVariant,
} from "./components/ui/button/index.js";
export {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "./components/ui/card/index.js";
export {
  DropdownMenu,
  DropdownMenuCheckboxGroup,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuGroupHeading,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
} from "./components/ui/dropdown-menu/index.js";
export { Input } from "./components/ui/input/index.js";
export {
  ScrollArea,
  ScrollAreaScrollbar,
} from "./components/ui/scroll-area/index.js";
export { Separator } from "./components/ui/separator/index.js";

export { default as ModeToggle } from "./components/ModeToggle.svelte";

export { default as CommitDetailPanel } from "./components/CommitDetailPanel.svelte";
export { default as CommitGraph } from "./components/CommitGraph.svelte";
export { default as CommitList } from "./components/CommitList.svelte";
export { default as CommitPanel } from "./components/CommitPanel.svelte";
export { default as ConfirmAction } from "./components/ConfirmAction.svelte";
export { default as ConnectionPanel } from "./components/ConnectionPanel.svelte";
export { default as DiffPanel } from "./components/DiffPanel.svelte";
export { default as RefsPanel } from "./components/RefsPanel.svelte";
export { default as RepositoryList } from "./components/RepositoryList.svelte";
export { default as StagingPanel } from "./components/StagingPanel.svelte";
export {
  default as StateBanner,
  type BannerState,
} from "./components/StateBanner.svelte";
export { default as StatusList } from "./components/StatusList.svelte";

export * from "./lib/format.js";
export * from "./lib/geometry.js";
export { cn } from "./lib/utils.js";
