/**
 * `@refyard/git-ui` — the workbench components.
 *
 * Everything here is driven by props and an injected `GitService`, and nothing imports
 * `$app/*`, so the same components can be mounted by the SvelteKit app, by a future
 * Kunkun plugin, or by a test harness. Routing and connection configuration are the
 * app's job; this package renders Git data and the states around it.
 *
 * The primitives under `components/ui/` are generated by the shadcn-svelte CLI
 * (`components.json` lives in this package) and then made self-contained by
 * `scripts/fix-shadcn-imports.ts`, which rewrites the CLI's `$lib/…` alias imports to
 * relative ones — this package is deliberately not a SvelteKit app, so it cannot rely on
 * that alias. Prefer generating another component over writing one.
 */

export {
  Badge,
  badgeVariants,
  type BadgeTone,
  type BadgeVariant,
} from "./components/ui/badge/index.js";
export {
  Button,
  buttonVariants,
  type ButtonSize,
  type ButtonVariant,
} from "./components/ui/button/index.js";
export {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "./components/ui/card/index.js";
export {
  DropdownMenu,
  DropdownMenuCheckboxGroup,
  DropdownMenuCheckboxItem,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuGroupHeading,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuPortal,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuSeparator,
  DropdownMenuShortcut,
  DropdownMenuSub,
  DropdownMenuSubContent,
  DropdownMenuSubTrigger,
  DropdownMenuTrigger,
} from "./components/ui/dropdown-menu/index.js";
export {
  ContextMenu,
  ContextMenuContent,
  ContextMenuItem,
  ContextMenuPortal,
  ContextMenuSeparator,
  ContextMenuTrigger,
} from "./components/ui/context-menu/index.js";
export { Input } from "./components/ui/input/index.js";
export {
  ScrollArea,
  ScrollAreaScrollbar,
} from "./components/ui/scroll-area/index.js";
export { Separator } from "./components/ui/separator/index.js";
export {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "./components/ui/collapsible/index.js";
export {
  Dialog,
  DialogTitle,
  DialogPortal,
  DialogFooter,
  DialogHeader,
  DialogTrigger,
  DialogOverlay,
  DialogContent,
  DialogDescription,
  DialogClose,
} from "./components/ui/dialog/index.js";
export {
  Popover,
  PopoverContent,
  PopoverDescription,
  PopoverHeader,
  PopoverTitle,
  PopoverTrigger,
  PopoverClose,
  PopoverPortal,
} from "./components/ui/popover/index.js";
export {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "./components/ui/tabs/index.js";
export {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
  TooltipProvider,
  TooltipPortal,
} from "./components/ui/tooltip/index.js";

export { default as ModeToggle } from "./components/ModeToggle.svelte";
export { default as RefyardLogo } from "./components/RefyardLogo.svelte";
export { default as SectionCard } from "./components/SectionCard.svelte";
export { default as SettingsDialog } from "./components/SettingsDialog.svelte";
export type { UpdateOffer, UpdatesProbe, UpdatesPhase } from "./lib/updates.js";
export { stepUpdates } from "./lib/updates.js";
export { default as AppearanceFields } from "./components/AppearanceFields.svelte";
export { default as ContextActionMenu } from "./components/ContextActionMenu.svelte";
export { default as ContextMenuLayer } from "./components/ContextMenuLayer.svelte";
export {
  closeContextMenu,
  createContextMenuState,
  openAnchoredContextMenu,
  openContextMenu,
  type ContextMenuState,
} from "./lib/context-menu.svelte.js";
export {
  HISTORY_COLUMN_IDS,
  columnLimits,
  defaultColumnState,
  loadStoredColumnState,
  parseColumnState,
  resizeColumn,
  serializeColumnState,
  storeColumnState,
  toggleColumn,
  visibleColumns,
  type HistoryColumnId,
  type HistoryColumnState,
} from "./lib/column-layout.js";
export {
  classifyCommitRef,
  commitRefDisplayName,
  type CommitRef,
} from "./lib/history-refs.js";
export { default as ConfirmDialog } from "./components/ConfirmDialog.svelte";

export { default as BranchPanel } from "./components/BranchPanel.svelte";
export { default as CommitDetailPanel } from "./components/CommitDetailPanel.svelte";
export { default as CommitGraph } from "./components/CommitGraph.svelte";
export { default as HistoryFilterBar } from "./components/HistoryFilterBar.svelte";
export type {
  HistoryFilterDraft,
  KnownHistoryPath,
} from "./lib/history-filters.js";
export { default as CommitList } from "./components/CommitList.svelte";
export { default as CommitPanel } from "./components/CommitPanel.svelte";
export { default as ConfirmAction } from "./components/ConfirmAction.svelte";
export { default as ConflictPanel } from "./components/ConflictPanel.svelte";
export { default as ConnectionPanel } from "./components/ConnectionPanel.svelte";
export { default as DiffPanel } from "./components/DiffPanel.svelte";
export { default as RefsPanel } from "./components/RefsPanel.svelte";
export { default as RemotePanel } from "./components/RemotePanel.svelte";
export { default as RepositoryList } from "./components/RepositoryList.svelte";
export {
  default as RepositoryAccessPanel,
  type ManagedRepository,
} from "./components/RepositoryAccessPanel.svelte";
export { default as RepositoryPanel } from "./components/RepositoryPanel.svelte";
export { default as RepositoryLauncher } from "./components/RepositoryLauncher.svelte";
export { default as ExecutionTargetPicker } from "./components/ExecutionTargetPicker.svelte";
export {
  default as RepositoryTabs,
  type RepositoryTabItem,
} from "./components/RepositoryTabs.svelte";
export type {
  CloneRequest as RepositoryCloneRequest,
  InitRequest as RepositoryInitRequest,
  WorkspaceRoot,
} from "./components/RepositoryPanel.svelte";
export { default as StagingPanel } from "./components/StagingPanel.svelte";
export { default as StashPanel } from "./components/StashPanel.svelte";
export {
  default as StateBanner,
  type BannerState,
} from "./components/StateBanner.svelte";
export { default as StatusList } from "./components/StatusList.svelte";
export { default as SubmodulePanel } from "./components/SubmodulePanel.svelte";
export { default as TagPanel } from "./components/TagPanel.svelte";
export { default as UncertainOutcomePanel } from "./components/UncertainOutcomePanel.svelte";
export { default as WorktreePanel } from "./components/WorktreePanel.svelte";
export { default as WorkbenchNav } from "./components/WorkbenchNav.svelte";
export type { WorkbenchNavItem } from "./components/WorkbenchNav.svelte";

export * from "./lib/format.js";
export * from "./lib/geometry.js";
export * from "./lib/execution-targets.js";
export { cn } from "./lib/utils.js";

export * from "./lib/context-actions.js";

export { default as WorkingCopyPanel } from "./components/WorkingCopyPanel.svelte";
export { default as WorktreeWipList } from "./components/WorktreeWipList.svelte";
