#!/usr/bin/env bun
/**
 * `pnpm build:release` — stage the publishable tarball contents.
 *
 * The staging directory (`packages/npm-dist`) holds a manifest that is source and
 * everything else that is generated: the CLI bundle, the web build, the bin shim and
 * a build-info file. Two rules shape the output:
 *
 * - **The artifact stands alone.** The CLI is bundled with its workspace packages
 *   inside it, so the tarball has no `dependencies` at all and nothing resolves
 *   `workspace:*` or a repository-relative path at run time.
 * - **The web build is required, not optional.** A CLI that starts and serves nothing
 *   is worse than a failed build, so this refuses to stage a package whose UI is
 *   missing rather than shipping a CLI-only install.
 *
 * No license file is written: this package is `UNLICENSED` and `private`, and
 * inventing a license on the project's behalf is not this script's call.
 */
import { execFile } from "node:child_process";
import {
  chmod,
  cp,
  mkdir,
  readFile,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";
import { build } from "esbuild";

const run = promisify(execFile);
const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const stagingRoot = join(repoRoot, "packages", "npm-dist");
const webBuild = join(repoRoot, "apps", "web", "build");
const distRoot = join(stagingRoot, "dist");
const binRoot = join(stagingRoot, "bin");

async function requireDirectory(
  path: string,
  what: string,
  hint: string,
): Promise<void> {
  try {
    const info = await stat(path);
    if (info.isDirectory()) {
      return;
    }
  } catch {
    // Falls through to the error below.
  }
  throw new Error(`${what} is missing at ${path}; ${hint}`);
}

/** The staged bytes must not name this checkout; a moved directory would break them. */
async function assertNoRepositoryPaths(
  files: readonly string[],
): Promise<void> {
  const marker = repoRoot;
  for (const file of files) {
    const contents = await readFile(file, "utf8");
    if (contents.includes(marker)) {
      throw new Error(
        `${relative(repoRoot, file)} names the build machine's checkout path (${marker}); the artifact must not`,
      );
    }
  }
}

const manifest = JSON.parse(
  await readFile(join(stagingRoot, "package.json"), "utf8"),
) as Record<string, unknown>;
for (const field of [
  "dependencies",
  "devDependencies",
  "optionalDependencies",
  "peerDependencies",
]) {
  const value = manifest[field];
  if (
    value !== undefined &&
    Object.keys(value as Record<string, string>).length > 0
  ) {
    throw new Error(
      `packages/npm-dist/package.json declares ${field}; the bundle carries its dependencies, so the published manifest must not`,
    );
  }
}

await requireDirectory(
  webBuild,
  "the web build",
  "run `pnpm build` first — the tarball ships the UI, and a CLI-only install serves nothing",
);

await rm(distRoot, { recursive: true, force: true });
await rm(binRoot, { recursive: true, force: true });
await mkdir(distRoot, { recursive: true });
await mkdir(binRoot, { recursive: true });

const builtAt = new Date().toISOString();
let gitCommit = "unknown";
try {
  const described = await run("git", ["rev-parse", "--short", "HEAD"], {
    cwd: repoRoot,
  });
  gitCommit = described.stdout.trim();
} catch {
  // A tarball built outside a checkout still records that the commit is unknown.
}

const cliOutfile = join(distRoot, "cli.mjs");
const result = await build({
  entryPoints: [join(repoRoot, "apps", "cli", "src", "bin.ts")],
  outfile: cliOutfile,
  bundle: true,
  platform: "node",
  format: "esm",
  // The floor the published `engines` promises (see scripts/bundle-cli.ts).
  target: "node22",
  // Workspace packages are bundled, so the artifact never resolves `workspace:*`.
  external: [],
  legalComments: "none",
  banner: {
    js: [
      "// refyard — generated bundle, not source.",
      "// This file is the CLI: it serves the UI in ./web and runs this machine's `git`.",
    ].join("\n"),
  },
  logLevel: "warning",
  metafile: true,
});
if (result.errors.length > 0) {
  console.error(
    `build:release: the CLI bundle failed with ${result.errors.length} error(s)`,
  );
  process.exit(1);
}

const binShim = [
  "#!/usr/bin/env node",
  "// Generated by scripts/build-release.ts. Start the CLI in ./dist/cli.mjs.",
  'import "../dist/cli.mjs";',
  "",
].join("\n");
const binPath = join(binRoot, "refyard.mjs");
await writeFile(binPath, binShim, "utf8");
await chmod(binPath, 0o755);

await cp(webBuild, join(stagingRoot, "web"), { recursive: true });

const bundleBytes = (await stat(cliOutfile)).size;
const buildInfo = {
  name: manifest["name"],
  version: manifest["version"],
  engines: manifest["engines"],
  builtAt,
  gitCommit,
  node: process.version,
  bundleBytes,
  entryPoints: Object.keys(result.metafile.outputs).length,
};
await writeFile(
  join(distRoot, "build-info.json"),
  `${JSON.stringify(buildInfo, null, 2)}\n`,
  "utf8",
);

await assertNoRepositoryPaths([cliOutfile, binPath]);

console.log(
  `build:release: staged ${relative(repoRoot, distRoot)} (bundle ${bundleBytes} bytes, commit ${gitCommit}) and ${relative(repoRoot, join(stagingRoot, "web"))}`,
);
