/**
 * Bundle the CLI so it can be run by real Node during development.
 *
 * Node 26 strips TypeScript types but does not rewrite the `.js` specifiers this
 * repository uses for relative imports (that convention is what keeps `git-core`
 * bundleable and boundary-checked), so running `apps/cli/src/bin.ts` directly only
 * works under a bundler-aware runtime such as bun. This script produces a single
 * ESM file with esbuild — the same bundler the neutral portability check uses — so
 * the CLI can also be exercised by Node itself.
 *
 * The output is generated build material under `.refyard-dev/`, which is ignored by
 * Git; nothing here is published. T13 owns the real packaging step, which bundles
 * the same entry point with `tsdown`, emits `bin/refyard.mjs`, and stages the web
 * assets next to it.
 */
import { cp, mkdir, rm, stat } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const repositoryRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const outfile = join(repositoryRoot, ".refyard-dev", "cli.mjs");
const webRoot = join(repositoryRoot, ".refyard-dev", "web");
const webBuild = join(repositoryRoot, "apps", "web", "build");

await mkdir(dirname(outfile), { recursive: true });

// The web build is staged next to the bundle, because that is the only place the CLI
// looks for a UI (`findWebRoot` checks `<cli dir>/web` and its parent). Without it the
// service serves its placeholder page — which is how the e2e suite passed on the
// machine this was written on: a symlink created by hand at `.refyard-dev/web`, and
// nothing else. Everywhere else, including CI, the page had no workbench in it and
// thirty specs failed on a missing panel.
async function stageWebBuild(): Promise<void> {
  try {
    const info = await stat(join(webBuild, "index.html"));
    if (!info.isFile()) {
      return;
    }
  } catch {
    console.warn(
      `bundle-cli: no web build at ${webBuild}; \`refyard open\` will serve the placeholder page`,
    );
    return;
  }
  await rm(webRoot, { recursive: true, force: true });
  await cp(webBuild, webRoot, { recursive: true });
  console.log(`bundle-cli: staged ${webBuild} at ${webRoot}`);
}

await stageWebBuild();
const result = await build({
  entryPoints: [join(repositoryRoot, "apps/cli/src/bin.ts")],
  outfile,
  bundle: true,
  platform: "node",
  format: "esm",
  // The floor the published `engines` promises: the bundle must parse there, not only on 26.
  target: "node22",
  // Workspace packages are bundled: the published artifact must not depend on
  // `workspace:*` specifiers resolving at run time.
  external: [],
  banner: {
    js: "// Generated by `bun scripts/bundle-cli.ts`; not source. Run `refyard doctor` for a real check.",
  },
  logLevel: "info",
});

if (result.errors.length > 0) {
  console.error(`bundle-cli: ${result.errors.length} error(s)`);
  process.exit(1);
}
console.log(`bundle-cli: wrote ${outfile}`);
