/**
 * Bundle the CLI so it can be run by real Node during development.
 *
 * Node 26 strips TypeScript types but does not rewrite the `.js` specifiers this
 * repository uses for relative imports (that convention is what keeps `git-core`
 * bundleable and boundary-checked), so running `apps/cli/src/bin.ts` directly only
 * works under a bundler-aware runtime such as bun. This script produces a single
 * ESM file with esbuild — the same bundler the neutral portability check uses — so
 * the CLI can also be exercised by Node itself.
 *
 * The output is generated build material under `.refyard-dev/`, which is ignored by
 * Git; nothing here is published. T13 owns the real packaging step, which bundles
 * the same entry point with `tsdown`, emits `bin/refyard.mjs`, and stages the web
 * assets next to it.
 */
import { mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const repositoryRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const outfile = join(repositoryRoot, ".refyard-dev", "cli.mjs");

await mkdir(dirname(outfile), { recursive: true });
const result = await build({
  entryPoints: [join(repositoryRoot, "apps/cli/src/bin.ts")],
  outfile,
  bundle: true,
  platform: "node",
  format: "esm",
  target: "node26",
  // Workspace packages are bundled: the published artifact must not depend on
  // `workspace:*` specifiers resolving at run time.
  external: [],
  banner: {
    js: "// Generated by `bun scripts/bundle-cli.ts`; not source. Run `refyard doctor` for a real check.",
  },
  logLevel: "info",
});

if (result.errors.length > 0) {
  console.error(`bundle-cli: ${result.errors.length} error(s)`);
  process.exit(1);
}
console.log(`bundle-cli: wrote ${outfile}`);
