/**
 * Bundle the CLI so it can be run by real Node during development.
 *
 * Node 26 strips TypeScript types but does not rewrite the `.js` specifiers this
 * repository uses for relative imports (that convention is what keeps `git-core`
 * bundleable and boundary-checked), so running `apps/cli/src/bin.ts` directly only
 * works under a bundler-aware runtime such as bun. This script produces a single
 * ESM file with esbuild — the same bundler the neutral portability check uses — so
 * the CLI can also be exercised by Node itself.
 *
 * The output is generated build material under `.refyard-dev/`, which is ignored by
 * Git; nothing here is published. The already-built static SPA is copied beside the CLI so
 * `pnpm cli` exercises the same local-workbench layout as the published package.
 */
import { cp, mkdir, rm, stat } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const repositoryRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const outfile = join(repositoryRoot, ".refyard-dev", "cli.mjs");
const webSource = join(repositoryRoot, "apps", "web", "build");
const webOut = join(repositoryRoot, ".refyard-dev", "web");

const webInfo = await stat(join(webSource, "200.html")).catch(() => null);
if (webInfo?.isFile() !== true) {
  throw new Error(
    "apps/web/build/200.html is missing; run `pnpm build:web` before bundling the CLI",
  );
}
await mkdir(dirname(outfile), { recursive: true });
await rm(webOut, { recursive: true, force: true });
await cp(webSource, webOut, { recursive: true });
const result = await build({
  entryPoints: [join(repositoryRoot, "apps/cli/src/bin.ts")],
  outfile,
  bundle: true,
  platform: "node",
  format: "esm",
  // The floor the published `engines` promises: the bundle must parse there, not only on 26.
  target: "node22",
  // Workspace packages are bundled: the published artifact must not depend on
  // `workspace:*` specifiers resolving at run time.
  external: [],
  banner: {
    js: "// Generated by `bun scripts/bundle-cli.ts`; not source. Run `refyard doctor` for a real check.",
  },
  logLevel: "info",
});

if (result.errors.length > 0) {
  console.error(`bundle-cli: ${result.errors.length} error(s)`);
  process.exit(1);
}
console.log(`bundle-cli: wrote ${outfile} and ${webOut}`);
